//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personalwebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLİLETİŞİM
    {
        public int ID { get; set; }
        public string ADSOYAD { get; set; }
        public string mail { get; set; }
        public string mesaj { get; set; }
        public string konu { get; set; }
    }
}
